name: "Vault Secret Fetch"
on: 
  push:
    branches: [ "main" ]

jobs:
  vault-check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Import Secrets from Vault"
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/webapp/config api_key | APP_SECRET

      - name: "Verify Secret Injection"
        run: |
          echo "Tentative de récupération du secret..."
          if [ -z "$APP_SECRET" ]; then
            echo "❌ ÉCHEC : Le secret est vide. Vérifie ton IP publique et ton Token."
            exit 1
          else
            echo "✅ SUCCÈS : Le secret a été récupéré depuis ton instance K8s !"
            # GitHub va masquer la valeur par *** par sécurité, c'est normal.
            echo "Valeur injectée : $APP_SECRET" 
          fi
